/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author Kyotsumi
 */
public class Matematicas extends javax.swing.JFrame {

    /**
     * Creates new form Matematicas
     */
    public Matematicas() {
        initComponents();
        transparenciaBoton();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        BotonExp = new javax.swing.JButton();
        BotonExam = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Volver.setBackground(new java.awt.Color(255, 255, 255));
        Volver.setForeground(new java.awt.Color(255, 0, 0));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, -1, -1));

        BotonExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMatematicas/MathPostExpTem.png"))); // NOI18N
        BotonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExpActionPerformed(evt);
            }
        });
        getContentPane().add(BotonExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        BotonExam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMatematicas/MathPostExam.png"))); // NOI18N
        BotonExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExamActionPerformed(evt);
            }
        });
        getContentPane().add(BotonExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMatematicas/MathMenu.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.setVisible(false);
        Menu a = new Menu();
        a.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void BotonExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExpActionPerformed
        this.setVisible(false);
        MathExp a = new MathExp();
        a.setVisible(true);
    }//GEN-LAST:event_BotonExpActionPerformed

    private void BotonExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExamActionPerformed
        this.setVisible(false);
        MathExamExp a = new MathExamExp();
        a.setVisible(true);
    }//GEN-LAST:event_BotonExamActionPerformed
    public void transparenciaBoton(){
        BotonExp.setOpaque(false);
        BotonExp.setContentAreaFilled(false);
        BotonExp.setBorderPainted(false);
        BotonExam.setOpaque(false);
        BotonExam.setContentAreaFilled(false);
        BotonExam.setBorderPainted(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matematicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonExam;
    private javax.swing.JButton BotonExp;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Volver;
    // End of variables declaration//GEN-END:variables
}
